### ISSUE TITLE
Special Request

### ISSUE THREAD

**Issue by Squidlers** [adepierre/SniffCraft#11]
Would you mind adding me on discord for some help and to answer a few complicated questions?

**Comment by Squidlers** [comment]
Username in my bio

**Comment by adepierre** [comment]
Hi! Unfortunately, I'm not using discord, so you'll have to detail your problem here.

**Comment by Squidlers** [comment]
I was looking for private help with this mod that possibly would require tweaking and adding things for what I'd like to do with it. Is there a place to chat?

**Comment by adepierre** [comment]
I'm not sure which mod you are refering to. Sniffcraft is not a minecraft mod but a standalone app. You can add all the things you want to it (as long as you respect the licence terms) with a PR or in your own fork.

Now if you have some issues, questions or stuff you don't understand well about it, you can ask here or in the discussions tab. You might not be the only one having the same questions, so having them asked and answered publicly is a big help for others too!

**Comment by Squidlers** [comment]
I guess. I was wondering if it was possible to hook SniffCraft up to a SOCKS5 Proxy used ingame on Minecraft. For example; login to a specific minecraft account and setup the proxy ingame (there is a proxy mod for that) then somehow linking that same SOCKS5 proxy to SniffCraft allowing you to see what packets are being sent to the command prompt or however this works, I am not too familiar yet. Reasoning behind is would allow you to see actions of an account from another computer or user

**Comment by adepierre** [comment]
I have like 0 knowledge of ingame proxy or how they work so I'm afraid I can't help you a lot.

If I understand it well, you'd like to "duplicate" the view of one client? So one client is playing "normally", and another client is just a duplicated view (like a stream, but using the minecraft data instead of a video stream).

If that's the case : I think it'll work well for incoming packets (so the world, entities etc... would be correctly displayed), but not for outgoing packets, as a lot of stuff done client side never go through the network. The server just trusts (to some extends) the client. For example, the movement of the player (=camera) would be very odd as it would not be synchronized very often.

**Comment by Squidlers** [comment]
Well in the case im referring to, I would have an account on another PC login to minecraft using a SOCKS5 Proxy and then I'd like to see the packets displayed on a stream like you said or with replay mod to see exactly what they are doing on my account. Basically I'm trying to see the actions done on an account live or with replay by the use of a proxy, im not sure if there's a way to login to that same proxy on a web network

**Comment by adepierre** [comment]
Closing it as unfortunately there is not much more that can be added about sniffcraft for this one.
