### ISSUE TITLE
Issue when connecting to server

### ISSUE THREAD

**Issue by NCBPFluffyBear** [adepierre/SniffCraft#15]
I'm getting this error when SniffCraft is running and I try to connect to `localhost`:
```
Starting new proxy to server-ip:25565
Empty mojang credentials, trying to authenticate using Microsoft account
[2022-08-16 23:31:44.118] [INFO] [(52208)] Authentifier.cpp(144): Cached Minecraft token for Microsoft account still valid.
Client --> Server: PARSING EXCEPTION: Wrong input size in ReadData || Hello
[0:0:0:0] [C --> S] Client Intention
[0:0:0:77] [S --> C] Hello
[0:0:0:269] [(SC) --> S] Key
Session closed
```
Anything I can do to resolve this?
Thanks

**Comment by adepierre** [comment]
Hello !

Could you check that your client/server version and the version for which you compiled sniffcraft are the same? If they're not that could explain the error.

Otherwise if you could detail the configuration so I can try to reproduce the error (server jar/version, client version, sniffcraft cmake generation command line etc...).

Thanks!

**Comment by NCBPFluffyBear** [comment]
That was the problem, thank you! The server was running ViaBackwards and connecting with the native version fixed it. Amazing project!
